from __future__ import annotations
"""Static Market Scanner indicator catalog."""


from backend.domain.market_scanner_models import (
    ScannerCostTier,
    ScannerIndicatorDefinition,
    ScannerIndicatorModule,
    ScannerIndicatorStatus,
    ScannerTimeframe,
)

DEFAULT_TIMEFRAMES: list[ScannerTimeframe] = ["5m", "15m", "1h", "1D"]
CATALOG_VERSION = "quantumbeta-v3.6-cmf-iv"

INDICATOR_AUDIT_STATUS: dict[str, tuple[ScannerIndicatorStatus, str]] = {
    "seven_day": (
        "proxy",
        "No hay metrica seven_day dedicada; se deriva de momentum/period change.",
    ),
    "signal": ("real", "Timeframe signal con score, direction, label y confidence."),
    "rsi": ("real", "Calcula TechnicalMath.rsi(close, 14)."),
    "rsi_hist": ("real", "Calcula TechnicalMath.rsi_hist(close, 14, 5)."),
    "macd": ("real", "Calcula macd, macd_signal y macd_hist."),
    "ema_7_14": ("real", "Cruce EMA 7/14 suma o resta votos."),
    "ema_21_42": ("real", "Cruce EMA 21/42 suma o resta votos."),
    "ema_100_200": ("real", "Cruce EMA 100/200 define regimen primario."),
    "avwap_vwap": (
        "real",
        "Session VWAP via TechnicalMath.vwap() — real HLC volume-weighted anchor.",
    ),
    "supertrend": ("real", "SuperTrend procesado en Phase A mediante TechnicalMath."),
    "bbp": ("real", "Bollinger Band Position procesado en Phase A mediante TechnicalMath."),
    "vix": ("real", "Global volatility context from ^VIX via FMP (market-wide proxy)."),
    "volume": ("real", "Usa volumen absoluto y relative_volume."),
    "prf": ("partial", "Usa ATR pct y period change como proxy de rango."),
    "relative_strength": (
        "proxy",
        "MTF Momentum proxy — not benchmark-relative strength vs SPY/sector.",
    ),
    "smc": (
        "real",
        "SMCEngine.analyze() ejecutado con barras OHLCV re-fetched en Phase B.",
    ),
    "market_structure": (
        "real",
        "MarketStructureEngine.process_frame() con detección MSS, sweeps y pools.",
    ),
    "fvg": (
        "real",
        "analyze_fvg_from_ohlcv(): FVGEngine lifecycle completo (detección + mitigación).",
    ),
    "vsa": (
        "real",
        "VSAEngine.analyze() con VSAForecastEngine; fallback básico si ia_probabilistico no disponible.",
    ),
    "volume_profile": (
        "partial",
        "OHLCV proxy por defecto; con SCANNER_REAL_DATA usa BingX trade+L2 (POC/VAH/VAL).",
    ),
    "order_flow_delta": (
        "partial",
        "OHLCV CVD proxy por defecto; con SCANNER_REAL_DATA usa tape BingX (CVD real).",
    ),
    "hmm_regime": (
        "real",
        "HMMInferenceEngine con parámetros default 3-estado (BULL_QUIET/MEAN_REVERT/CRISIS).",
    ),
    "tail_risk": (
        "real",
        "TailRiskEngine ejecutado con smile de opciones si existe snapshot; fallback ATR pct.",
    ),
    "jump_risk": (
        "real",
        "Análisis de curtosis de retornos logarítmicos para detectar fat-tails/jumps.",
    ),
    "regime": (
        "real",
        "MarkovRegimeEngine (HMM) 3-estado (BULL_QUIET/BEAR_VOLATILE/CHAOTIC).",
    ),
    "expected_move": (
        "real",
        "ExpectedMoveEngine: 1-sigma range (7d) con IV real o proxy de volatilidad.",
    ),
    "squeeze": (
        "real",
        "SqueezeIgnitionEngine: FSM (Vulnerable/Ignition) con Delta-Hedging MM logic.",
    ),
    "net_gex": ("real", "Lee gex_levels.net_gex_total del options snapshot."),
    "dealer_bias": ("real", "Lee gex_levels.dealer_bias del options snapshot."),
    "gamma_flip": ("real", "Lee zero_gamma_level del snapshot de opciones."),
    "squeeze_probability": ("real", "Lee gex_levels.squeeze_probability del snapshot."),
    "iv_vol_term": ("real", "Lee contango/backwardation del term structure en iv_surface."),
    "flow_signal": ("partial", "Lee flow_signal.label/signal cuando el snapshot lo trae."),
    "obv_oi": (
        "partial",
        "OBV × sign(ΔOI_net) × (1 + |ΔOI_net|/OI_avg); merge_asof OHLCV + options OI ATM.",
    ),
    "mfi_flow": (
        "partial",
        "clamp(MFI(14) × Flow_ratio_norm); ratio Call$/Put$ / SMA(20); merge_asof OHLCV + flow.",
    ),
    "cmf_iv": (
        "partial",
        "(CMF / IV_pct_norm) × Vega_sign; IV crush filter iv_pct≥0.80; unbounded conviction scale.",
    ),
    "vpin": (
        "proxy",
        "OHLCV VPIN proxy por defecto; con SCANNER_REAL_DATA usa tape BingX (vpin_trade_tape_v1).",
    ),
    "lob_microstructure": (
        "partial",
        "Señales LOB/micro desde snapshot microstructure_confluence cuando existen; sin libro L2 completo.",
    ),
    "sentiment_adjusted_rsi": (
        "proxy",
        "RSI ajustado por sentimiento/catalyst del context rail (POST /fusion-enrich).",
    ),
    "sentiment_adjusted_momentum": (
        "proxy",
        "MACD hist escalado por tono de sentimiento/catalyst (POST /fusion-enrich).",
    ),
    "composite_flow_fusion": (
        "proxy",
        "Índice 0–100 de flujo: OFI/VPIN/imbalance + sentimiento + riesgo de evento.",
    ),
    "news_catalyst_alignment": (
        "proxy",
        "Alineación noticia/precio y catalizador vs acción y volatilidad relativa.",
    ),
    "regime_sentiment_score": (
        "proxy",
        "Regimen RSI × tono de sentimiento y riesgo de catalizador.",
    ),
    "bull_bear_fusion_index": (
        "proxy",
        "Índice compuesto técnico + sentimiento + catalizador + flujo (desk fusion).",
    ),
    "fund_liquidity_ttm": (
        "partial",
        "Liquidez TTM (current/quick) desde FMP ratios-ttm cuando la clave está disponible.",
    ),
    "fund_quality_ttm": (
        "partial",
        "Calidad de balance/ROE TTM desde FMP ratios-ttm (heurística de scoring).",
    ),
    "macro_desk_overlay": (
        "proxy",
        "Overlay macro/micro determinístico; calendario FRED/FMP pendiente de cableado.",
    ),
}


def _supported(weights: dict[str, float]) -> list[ScannerTimeframe]:
    order: list[ScannerTimeframe] = ["5m", "15m", "1h", "1D"]
    return [timeframe for timeframe in order if timeframe in weights]


def _indicator(
    *,
    key: str,
    label: str,
    module: ScannerIndicatorModule,
    description: str,
    weights: dict[str, float],
    cost_tier: ScannerCostTier,
    default_enabled: bool = True,
    requires: list[str] | None = None,
) -> ScannerIndicatorDefinition:
    status, status_detail = INDICATOR_AUDIT_STATUS.get(key, ("proxy", "Audit status pending."))
    return ScannerIndicatorDefinition(
        key=key,
        label=label,
        module=module,
        description=description,
        default_enabled=default_enabled,
        supports_timeframes=_supported(weights),
        weight_by_timeframe=weights,
        cost_tier=cost_tier,
        requires=requires or [],
        status=status,
        status_detail=status_detail,
    )


DEFAULT_SCANNER_INDICATORS: tuple[ScannerIndicatorDefinition, ...] = (
    _indicator(
        key="seven_day",
        label="7D",
        module="core",
        description="Seven-day price change used as compact momentum context.",
        weights={"1D": 0.8},
        cost_tier="cheap",
    ),
    _indicator(
        key="signal",
        label="Signal",
        module="core",
        description="Fast deterministic timeframe signal.",
        weights={"5m": 1.5, "15m": 1.5, "1h": 1.4, "1D": 1.2},
        cost_tier="cheap",
    ),
    _indicator(
        key="rsi",
        label="RSI",
        module="core",
        description="RSI momentum zone and extension pressure.",
        weights={"5m": 1.1, "15m": 0.8, "1h": 1.0, "1D": 0.9},
        cost_tier="cheap",
    ),
    _indicator(
        key="rsi_hist",
        label="RSI Hist",
        module="core",
        description="RSI trend proxy from recent oscillator behavior.",
        weights={"5m": 0.0, "15m": 0.8, "1h": 0.8, "1D": 0.8},
        cost_tier="cheap",
        requires=["rsi"],
    ),
    _indicator(
        key="macd",
        label="MACD",
        module="core",
        description="MACD histogram and signal-line momentum.",
        weights={"5m": 1.5, "15m": 1.1, "1h": 1.2, "1D": 1.0},
        cost_tier="cheap",
    ),
    _indicator(
        key="ema_7_14",
        label="EMA 7/14",
        module="core",
        description="Short trend impulse.",
        weights={"5m": 1.5, "15m": 1.1, "1h": 1.1, "1D": 0.7},
        cost_tier="cheap",
    ),
    _indicator(
        key="ema_21_42",
        label="EMA 21/42",
        module="core",
        description="Intermediate trend filter.",
        weights={"5m": 1.0, "15m": 1.0, "1h": 1.3, "1D": 1.2},
        cost_tier="cheap",
    ),
    _indicator(
        key="ema_100_200",
        label="EMA 100/200",
        module="core",
        description="Primary trend regime filter.",
        weights={"5m": 0.2, "15m": 0.5, "1h": 1.1, "1D": 2.0},
        cost_tier="cheap",
    ),
    _indicator(
        key="avwap_vwap",
        label="Session VWAP",
        module="core",
        description="Session VWAP (not Anchored VWAP) — confluence and mean location.",
        weights={"5m": 1.0, "15m": 1.5, "1h": 1.2, "1D": 0.9},
        cost_tier="cheap",
    ),
    _indicator(
        key="supertrend",
        label="SuperTrend",
        module="core",
        description="ATR-adjusted trend proxy.",
        weights={"5m": 1.0, "15m": 1.2, "1h": 1.2, "1D": 1.2},
        cost_tier="cheap",
        requires=["atr"],
    ),
    _indicator(
        key="bbp",
        label="BBP",
        module="core",
        description="Bollinger band position proxy.",
        weights={"5m": 0.8, "15m": 0.8, "1h": 1.1, "1D": 1.1},
        cost_tier="cheap",
    ),
    _indicator(
        key="vix",
        label="VIX",
        module="core",
        description="Broad volatility context when available.",
        weights={"1D": 0.0},
        cost_tier="cheap",
        default_enabled=False,
    ),
    _indicator(
        key="volume",
        label="Vol",
        module="core",
        description="Absolute and relative volume confirmation.",
        weights={"5m": 1.6, "15m": 1.5, "1h": 1.1, "1D": 1.0},
        cost_tier="cheap",
    ),
    _indicator(
        key="prf",
        label="PRF",
        module="core",
        description="Price range filter from ATR and period change.",
        weights={"5m": 0.8, "15m": 0.8, "1h": 0.9, "1D": 1.0},
        cost_tier="cheap",
    ),
    _indicator(
        key="relative_strength",
        label="MTF Momentum",
        module="core",
        description="Relative strength proxy from multi-timeframe momentum.",
        weights={"5m": 0.8, "15m": 0.8, "1h": 1.0, "1D": 2.0},
        cost_tier="cheap",
    ),
    _indicator(
        key="smc",
        label="SMC",
        module="technical",
        description="Smart-money concepts summary for Phase B candidates.",
        weights={"5m": 2.0, "15m": 2.2, "1h": 2.3, "1D": 1.8},
        cost_tier="phase_b",
    ),
    _indicator(
        key="market_structure",
        label="Market Structure",
        module="technical",
        description="Swing structure, BOS, CHoCH and higher-timeframe alignment proxy.",
        weights={"5m": 0.9, "15m": 1.8, "1h": 2.2, "1D": 2.5},
        cost_tier="phase_b",
    ),
    _indicator(
        key="fvg",
        label="FVG",
        module="technical",
        description="Fair-value-gap pressure proxy.",
        weights={"15m": 2.0, "1h": 1.8, "1D": 1.2},
        cost_tier="phase_b",
    ),
    _indicator(
        key="vsa",
        label="VSA",
        module="technical",
        description="Volume-spread analysis proxy.",
        weights={"5m": 1.8, "15m": 2.5, "1h": 1.6, "1D": 1.0},
        cost_tier="phase_b",
    ),
    _indicator(
        key="volume_profile",
        label="Volume Profile",
        module="technical",
        description="Volume node and acceptance context.",
        weights={"15m": 0.6, "1h": 0.8, "1D": 1.0},
        cost_tier="phase_b",
        default_enabled=False,
    ),
    _indicator(
        key="order_flow_delta",
        label="Order Flow Delta",
        module="technical",
        description="Delta pressure proxy when order-flow data exists.",
        weights={"5m": 2.2, "15m": 1.5},
        cost_tier="phase_b",
        default_enabled=False,
    ),
    _indicator(
        key="hmm_regime",
        label="HMM Regime",
        module="technical",
        description="Hidden Markov regime proxy for Phase B.",
        weights={"1h": 1.3, "1D": 2.0},
        cost_tier="phase_b",
        default_enabled=False,
    ),
    _indicator(
        key="tail_risk",
        label="Tail Risk",
        module="probabilistic",
        description="Local OHLCV tail-risk proxy.",
        weights={"5m": 0.7, "15m": 0.8, "1h": 1.2, "1D": 1.8},
        cost_tier="phase_b",
    ),
    _indicator(
        key="jump_risk",
        label="Jump Risk",
        module="probabilistic",
        description="Gap and jump-risk proxy from realized moves.",
        weights={"5m": 0.9, "15m": 0.8, "1h": 0.9, "1D": 1.1},
        cost_tier="phase_b",
    ),
    _indicator(
        key="regime",
        label="Regime",
        module="probabilistic",
        description="Quant regime proxy from volatility and trend.",
        weights={"1h": 2.0, "1D": 2.5},
        cost_tier="phase_b",
    ),
    _indicator(
        key="expected_move",
        label="Expected Move",
        module="probabilistic",
        description="ATR-implied expected move context.",
        weights={"5m": 0.7, "15m": 0.7, "1h": 0.9, "1D": 1.3},
        cost_tier="phase_b",
    ),
    _indicator(
        key="squeeze",
        label="Squeeze",
        module="probabilistic",
        description="Compression and volatility-expansion probability proxy.",
        weights={"5m": 0.8, "15m": 1.0, "1h": 1.1, "1D": 1.0},
        cost_tier="phase_b",
    ),
    _indicator(
        key="net_gex",
        label="Net GEX",
        module="options_gex",
        description="Net gamma exposure when options snapshot is available.",
        weights={"5m": 2.5, "15m": 2.3, "1h": 1.4, "1D": 0.8},
        cost_tier="cached_external",
    ),
    _indicator(
        key="dealer_bias",
        label="Dealer Bias",
        module="options_gex",
        description="Dealer positioning bias from cached options context.",
        weights={"5m": 1.0, "15m": 0.9, "1h": 1.5, "1D": 2.2},
        cost_tier="cached_external",
    ),
    _indicator(
        key="gamma_flip",
        label="Gamma Flip",
        module="options_gex",
        description="Gamma flip distance when available.",
        weights={"1h": 1.2, "1D": 1.5},
        cost_tier="cached_external",
    ),
    _indicator(
        key="squeeze_probability",
        label="Squeeze Probability",
        module="options_gex",
        description="Options-informed squeeze probability.",
        weights={"15m": 1.0, "1h": 1.1, "1D": 1.0},
        cost_tier="cached_external",
    ),
    _indicator(
        key="iv_vol_term",
        label="IV/Vol Term",
        module="options_gex",
        description="Implied-volatility term context.",
        weights={"1h": 1.0, "1D": 1.3},
        cost_tier="cached_external",
    ),
    _indicator(
        key="flow_signal",
        label="Flow Signal",
        module="options_gex",
        description="Options flow signal when cached flow exists.",
        weights={"1h": 1.3, "1D": 1.5},
        cost_tier="cached_external",
    ),
    _indicator(
        key="obv_oi",
        label="OBV-OI",
        module="options_gex",
        description="OBV fused with net OI delta (ATM chain); amplifies only when OI moves.",
        weights={"5m": 2.0, "15m": 1.8, "1h": 0.6},
        cost_tier="cached_external",
        requires=["volume"],
    ),
    _indicator(
        key="mfi_flow",
        label="MFI-Flow",
        module="options_gex",
        description="MFI × normalized call/put premium flow; clamp 0–100 preserves OB/OS thresholds.",
        weights={"5m": 1.8, "15m": 1.6, "1h": 0.8},
        cost_tier="cached_external",
        requires=["volume"],
    ),
    _indicator(
        key="cmf_iv",
        label="CMF-IV",
        module="options_gex",
        description="CMF / IV percentile × Vega sign; penalizes high-IV noise, confirms with ATM Vega.",
        weights={"5m": 1.6, "15m": 1.8, "1h": 1.0},
        cost_tier="cached_external",
        requires=["volume"],
    ),
    _indicator(
        key="vpin",
        label="VPIN Proxy",
        module="technical",
        description="Volume-synchronized toxicity proxy from OHLCV (institutional desk microstructure).",
        weights={"5m": 1.8, "15m": 1.6, "1h": 1.2, "1D": 0.6},
        cost_tier="cheap",
    ),
    _indicator(
        key="lob_microstructure",
        label="LOB / Micro Confluence",
        module="technical",
        description="Microstructure hints when options snapshot exposes confluence payloads.",
        weights={"5m": 1.0, "15m": 1.0, "1h": 1.2, "1D": 1.0},
        cost_tier="phase_b",
    ),
    _indicator(
        key="sentiment_adjusted_rsi",
        label="Sent. RSI",
        module="core",
        description="RSI adjusted by context-rail sentiment and catalyst tone (fusion enrich).",
        weights={"5m": 0.4, "15m": 0.6, "1h": 0.8, "1D": 0.8},
        cost_tier="cheap",
        default_enabled=False,
    ),
    _indicator(
        key="sentiment_adjusted_momentum",
        label="Sent. Mom.",
        module="core",
        description="MACD histogram scaled by sentiment/catalyst alignment (fusion enrich).",
        weights={"5m": 0.3, "15m": 0.5, "1h": 0.8, "1D": 0.5},
        cost_tier="cheap",
        default_enabled=False,
    ),
    _indicator(
        key="composite_flow_fusion",
        label="Flow Fusion",
        module="core",
        description="Composite microstructure flow score blended with sentiment (fusion enrich).",
        weights={"5m": 0.4, "15m": 0.6, "1h": 0.8, "1D": 0.5},
        cost_tier="cheap",
        default_enabled=False,
    ),
    _indicator(
        key="news_catalyst_alignment",
        label="News Align",
        module="core",
        description="Alignment of tape move vs sentiment and catalyst risk (fusion enrich).",
        weights={"5m": 0.2, "15m": 0.4, "1h": 0.5, "1D": 0.8},
        cost_tier="cheap",
        default_enabled=False,
    ),
    _indicator(
        key="regime_sentiment_score",
        label="Regime × Sent.",
        module="core",
        description="RSI regime convexity with sentiment and catalyst overlay (fusion enrich).",
        weights={"5m": 0.3, "15m": 0.5, "1h": 0.8, "1D": 0.8},
        cost_tier="cheap",
        default_enabled=False,
    ),
    _indicator(
        key="bull_bear_fusion_index",
        label="Bull/Bear Fusion",
        module="core",
        description="Desk fusion index: scanner score, RSI, sentiment, catalyst, flow (fusion enrich).",
        weights={"5m": 0.3, "15m": 0.6, "1h": 0.8, "1D": 1.0},
        cost_tier="cheap",
        default_enabled=False,
    ),
    _indicator(
        key="fund_liquidity_ttm",
        label="Fund. Liquidity",
        module="fundamentals",
        description="Current / quick ratios (TTM) from FMP when Phase B fundamentals module is enabled.",
        weights={"1D": 1.6, "1h": 1.0, "15m": 0.6, "5m": 0.4},
        cost_tier="cached_external",
        requires=["fmp_key"],
    ),
    _indicator(
        key="fund_quality_ttm",
        label="Fund. Quality",
        module="fundamentals",
        description="ROE / leverage heuristics from FMP ratios TTM snapshot.",
        weights={"1D": 1.5, "1h": 1.0, "15m": 0.6, "5m": 0.4},
        cost_tier="cached_external",
        requires=["fmp_key"],
    ),
    _indicator(
        key="macro_desk_overlay",
        label="Macro Desk",
        module="macro_micro",
        description="Deterministic macro/micro desk overlay (upgrade path: economic calendar + cross-assets).",
        weights={"1D": 1.2, "1h": 1.0, "15m": 0.8, "5m": 0.5},
        cost_tier="cheap",
    ),
)


def list_indicator_definitions() -> list[ScannerIndicatorDefinition]:
    """Return a copy of the static scanner indicator catalog."""
    return list(DEFAULT_SCANNER_INDICATORS)
