"""Umbrales relajados para más operaciones en bots Alpaca/BingX/Options. # [PD-8][TH]"""

from __future__ import annotations

import os

# Alpaca decision engine
ALPACA_RELAXED_MIN_VOLUME_Z: float = 0.30
ALPACA_RELAXED_MIN_CLOSE_POSITION: float = 0.35
ALPACA_RELAXED_PROB_FLOOR: float = 0.35
ALPACA_RELAXED_SIZE_DOWN_BAND: float = 0.15
ALPACA_RELAXED_R2_MIN_SCORE: float = 32.0
ALPACA_RELAXED_R2_GATE_VETO: float = 0.05
ALPACA_RELAXED_R2_CONFLUENCE_MIN: int = 1

# BingX decision engine
BINGX_RELAXED_MIN_DECISION_SCORE: float = 0.30
BINGX_RELAXED_MIN_PREDICTIVE_CONF: float = 0.25
BINGX_RELAXED_SIZE_DOWN_BAND: float = 0.18

# Verificación — sizing discovery (más P&L visible en paper/VST)
VERIFICATION_ALPACA_NOTIONAL_USD: float = 2_000.0
VERIFICATION_BINGX_NOTIONAL_USDT: float = 500.0
VERIFICATION_EXECUTION_COOLDOWN_MINUTES: float = 3.0
OPTIONS_CONTRACT_QTY: int = 2
OPTIONS_PREMIUM_SCALE_MULT: float = 1.5
ALPACA_OPTIONS_R1_MAX_PER_CYCLE: int = 6
ALPACA_OPTIONS_R2_MAX_PER_CYCLE: int = 3

# Options Strategy vetos
OPTIONS_RELAXED_MIN_GLOBAL_CONFIDENCE: float = 0.52
OPTIONS_RELAXED_MIN_CHAIN_LIQUIDITY: float = 0.22
OPTIONS_RELAXED_TAIL_RISK_THRESHOLD: float = 0.92
OPTIONS_RELAXED_FLOW_TOXIC_CONVICTION: float = 0.10
OPTIONS_RELAXED_FLOW_TOXIC_DISPERSION: float = 0.82
OPTIONS_RELAXED_GAMMA_PRESSURE: float = 0.88

# Options Strategy universo R1 (11 tickers)
OPTIONS_ROUTE1_DTE_MIN: int = 3
OPTIONS_ROUTE1_DTE_MAX: int = 45
OPTIONS_ROUTE1_MIN_OPEN_INTEREST: int = 100
OPTIONS_ROUTE1_MIN_DAILY_VOLUME: int = 25
OPTIONS_CHAIN_HYDRATION_MIN_LEGS: int = 4

# Risk-adjusted confidence sizing (Kelly + regime + heat)
OPTIONS_KELLY_FRACTION: float = 0.5
OPTIONS_KELLY_MAX_FRACTION: float = 0.25
OPTIONS_CONFIDENCE_SIZE_FLOOR: float = 0.35
OPTIONS_DISPERSION_PENALTY: float = 0.35
OPTIONS_MAX_RISK_BUDGET_PCT: float = 1.875
OPTIONS_MAX_PORTFOLIO_HEAT_PCT: float = 12.0
OPTIONS_MAX_SECTOR_HEAT_PCT: float = 5.0
OPTIONS_CORRELATION_PENALTY_PER_SYMBOL: float = 0.15
OPTIONS_CORRELATION_SIZE_FLOOR: float = 0.55
SIZING_VIX_ELEVATED: float = 25.0
SIZING_VIX_HIGH: float = 30.0
SIZING_REGIME_SCALAR_HIGH: float = 0.4
SIZING_REGIME_SCALAR_ELEVATED: float = 0.65
SIZING_REGIME_SCALAR_NORMAL: float = 1.0
SIZING_ATR_TO_VIX_SCALE: float = 5.0
ALPACA_CONFIDENCE_SIZE_FLOOR: float = 0.4
BINGX_TRADE_SIZE_PCT: float = 0.01
BINGX_VIX_PROXY: float = 20.0

# Bot loop — dual-interval (Wall Street style: fast monitor + slow scan)
DEFAULT_BOT_CYCLE_INTERVAL_S: int = 240
BOT_DUAL_LOOP_ENABLED: bool = True
BOT_FAST_CYCLE_INTERVAL_S: int = 75
BOT_SLOW_CYCLE_INTERVAL_S: int = 240

# Cuentas paper/demo objetivo
ALPACA_PAPER_EQUITY_USD: float = 100_000.0
BINGX_DEMO_EQUITY_USDT: float = 99_998.8102
ALPACA_NOTIONAL_PER_TRADE_USD: float = 2_500.0
BINGX_NOTIONAL_PER_TRADE_USDT: float = 2_000.0


def apply_paper_demo_account_env(*, execute_orders: bool = True) -> None:
    """Configura Alpaca paper 100k + BingX VST demo ~100k USDT y risk desk acorde."""
    apply_relaxed_bot_env(execute_orders=execute_orders)
    forced: dict[str, str] = {
        "ALPACA_TRADING_MODE": "paper",
        "ALPACA_NOTIONAL_PER_TRADE_USD": str(ALPACA_NOTIONAL_PER_TRADE_USD),
        "ALPACA_BUYING_POWER_PCT": "0.025",
        "ALPACA_MAX_OPEN_POSITIONS": "10",
        "BINGX_BOT_TRADING_ENV": "prod-vst",
        "BINGX_EQUITY_USDT": str(BINGX_DEMO_EQUITY_USDT),
        "BINGX_NOTIONAL_PER_TRADE_USDT": str(BINGX_NOTIONAL_PER_TRADE_USDT),
        "RISK_MAX_POSITION_NOTIONAL_USDT": "75000",
        "RISK_MAX_SYMBOL_EXPOSURE_USDT": "15000",
        "RISK_MAX_OPEN_POSITIONS": "10",
        "RISK_MAX_DAILY_LOSS_USDT": "5000",
        "RISK_MIN_L2_QUALITY_SCORE": "0",
        "BINGX_RISK_REQUIRES_L2": "false",
        "BINGX_ZONE_VETO_ENABLED": "false",
        "BINGX_EXEC_QUALITY_ENABLED": "false",
    }
    if execute_orders:
        forced["ALPACA_DRY_RUN"] = "false"
        forced["BINGX_DRY_RUN"] = "false"
        forced["BINGX_BOT_ENABLE_LIVE"] = "true"
    _force_env(forced)


def _force_env(updates: dict[str, str]) -> None:
    """Sobrescribe variables de entorno (no setdefault)."""
    for key, value in updates.items():
        os.environ[key] = value


def apply_verification_session_env(*, execute_orders: bool = True) -> None:
    """Modo verificación: umbrales bajos, notional pequeño, auditoría completa."""
    apply_paper_demo_account_env(execute_orders=execute_orders)
    _force_env(
        {
            "ALPACA_MIN_VOLUME_Z": str(ALPACA_RELAXED_MIN_VOLUME_Z),
            "ALPACA_MIN_CLOSE_POSITION": str(ALPACA_RELAXED_MIN_CLOSE_POSITION),
            "ALPACA_PROB_FLOOR": str(ALPACA_RELAXED_PROB_FLOOR),
            "ALPACA_SIZE_DOWN_BAND": str(ALPACA_RELAXED_SIZE_DOWN_BAND),
            "ALPACA_R2_MIN_SCORE": str(ALPACA_RELAXED_R2_MIN_SCORE),
            "ALPACA_R2_GATE_VETO_THRESHOLD": str(ALPACA_RELAXED_R2_GATE_VETO),
            "ALPACA_R2_CONFLUENCE_MIN_ENGINES": str(ALPACA_RELAXED_R2_CONFLUENCE_MIN),
            "ALPACA_R2_HMM_BULLISH_ONLY": "false",
            "ALPACA_R2_VSA_VOLUME_GATE": "false",
            "ALPACA_R2_ACCEPT_S1": "true",
            "ALPACA_VERIFICATION_RELAXED_BULLISH": "true",
            "ALPACA_PREDICTIVE_GATE_DISABLED": "true",
            "EQUITY_OPTIONS_GATE_RELAXED": "true",
            "EQUITY_L2_GATE_ENABLED": "false",
            "EQUITY_L2_GATE_BLOCK_MISSING": "false",
            "BINGX_MIN_DECISION_SCORE": str(BINGX_RELAXED_MIN_DECISION_SCORE),
            "BINGX_MIN_PREDICTIVE_CONFIDENCE": str(BINGX_RELAXED_MIN_PREDICTIVE_CONF),
            "BINGX_SKIP_OPTIONS_SNAPSHOT": "true",
            "BINGX_TWAP_SLIVERING_ENABLED": "false",
            "BOT_EXECUTION_COOLDOWN_MINUTES": str(VERIFICATION_EXECUTION_COOLDOWN_MINUTES),
            "BOT_DUAL_LOOP_ENABLED": "true",
            "BOT_FAST_CYCLE_INTERVAL_S": str(BOT_FAST_CYCLE_INTERVAL_S),
            "BOT_SLOW_CYCLE_INTERVAL_S": str(BOT_SLOW_CYCLE_INTERVAL_S),
            "BOT_CYCLE_INTERVAL_S": str(BOT_SLOW_CYCLE_INTERVAL_S),
            "RISK_COOLDOWN_AFTER_LOSS_MINUTES": "2",
            "ALPACA_NOTIONAL_PER_TRADE_USD": str(VERIFICATION_ALPACA_NOTIONAL_USD),
            "BINGX_NOTIONAL_PER_TRADE_USDT": str(VERIFICATION_BINGX_NOTIONAL_USDT),
            "BINGX_USE_STATIC_NOTIONAL": "true",
            "BINGX_OMIT_REDUCE_ONLY": "true",
            "TECHNICAL_CPU_TIMEOUT_SEC": "15",
            "OPTIONS_CONTRACT_QTY": str(OPTIONS_CONTRACT_QTY),
            "OPTIONS_PREMIUM_SCALE_MULT": str(OPTIONS_PREMIUM_SCALE_MULT),
            "ALPACA_OPTIONS_R1_MAX_PER_CYCLE": str(ALPACA_OPTIONS_R1_MAX_PER_CYCLE),
            "ALPACA_OPTIONS_R2_MAX_PER_CYCLE": str(ALPACA_OPTIONS_R2_MAX_PER_CYCLE),
            "ALPACA_OPTIONS_R2_MIN_GLOBAL_CONFIDENCE": "0.35",
            "OPTIONS_STRATEGY_RELAXED_VETOS": "true",
            "OPTIONS_STRATEGY_MIN_GLOBAL_CONFIDENCE": "0.18",
            "OPTIONS_RELAXED_MIN_CHAIN_LIQUIDITY": str(OPTIONS_RELAXED_MIN_CHAIN_LIQUIDITY),
            "OPTIONS_UNIVERSE_DTE_MIN": str(OPTIONS_ROUTE1_DTE_MIN),
            "OPTIONS_UNIVERSE_DTE_MAX": str(OPTIONS_ROUTE1_DTE_MAX),
            "OPTIONS_MIN_OPEN_INTEREST": str(OPTIONS_ROUTE1_MIN_OPEN_INTEREST),
            "OPTIONS_MIN_DAILY_VOLUME": str(OPTIONS_ROUTE1_MIN_DAILY_VOLUME),
            "OPTIONS_CHAIN_HYDRATION_MIN_LEGS": str(OPTIONS_CHAIN_HYDRATION_MIN_LEGS),
            "OPTIONS_ROUTE1_LENIENT": "true",
            "ALPACA_OPTIONS_ENABLED": "true",
            "ALPACA_OPTIONS_PRIORITY_EQUITY": "true",
            "ALPACA_OPTIONS_R1_RISK_MULT": "1.5",
            "ALPACA_OPTIONS_R2_RISK_MULT": "0.85",
            "ALPACA_BUYING_POWER_PCT": "0.05",
            "OPTIONS_KELLY_FRACTION": str(OPTIONS_KELLY_FRACTION),
            "OPTIONS_KELLY_MAX_FRACTION": str(OPTIONS_KELLY_MAX_FRACTION),
            "OPTIONS_CONFIDENCE_SIZE_FLOOR": str(OPTIONS_CONFIDENCE_SIZE_FLOOR),
            "OPTIONS_DISPERSION_PENALTY": str(OPTIONS_DISPERSION_PENALTY),
            "OPTIONS_MAX_RISK_BUDGET_PCT": str(OPTIONS_MAX_RISK_BUDGET_PCT),
            "OPTIONS_MAX_PORTFOLIO_HEAT_PCT": str(OPTIONS_MAX_PORTFOLIO_HEAT_PCT),
            "OPTIONS_MAX_SECTOR_HEAT_PCT": str(OPTIONS_MAX_SECTOR_HEAT_PCT),
            "OPTIONS_CORRELATION_PENALTY_PER_SYMBOL": str(OPTIONS_CORRELATION_PENALTY_PER_SYMBOL),
            "OPTIONS_CORRELATION_SIZE_FLOOR": str(OPTIONS_CORRELATION_SIZE_FLOOR),
            "SIZING_VIX_ELEVATED": str(SIZING_VIX_ELEVATED),
            "SIZING_VIX_HIGH": str(SIZING_VIX_HIGH),
            "SIZING_REGIME_SCALAR_HIGH": str(SIZING_REGIME_SCALAR_HIGH),
            "SIZING_REGIME_SCALAR_ELEVATED": str(SIZING_REGIME_SCALAR_ELEVATED),
            "SIZING_REGIME_SCALAR_NORMAL": str(SIZING_REGIME_SCALAR_NORMAL),
            "SIZING_ATR_TO_VIX_SCALE": str(SIZING_ATR_TO_VIX_SCALE),
            "ALPACA_CONFIDENCE_SIZE_FLOOR": str(ALPACA_CONFIDENCE_SIZE_FLOOR),
            "BINGX_TRADE_SIZE_PCT": str(BINGX_TRADE_SIZE_PCT),
            "BINGX_VIX_PROXY": str(BINGX_VIX_PROXY),
            "ALPACA_EOD_FLATTEN_ENABLED": "false",
            "ALPACA_EOD_ENTRY_CUTOFF_DISABLED": "true",
            "ALPACA_EOD_ENTRY_CUTOFF_ET": "15:30",
            "ALPACA_EOD_FLATTEN_START_ET": "15:45",
        }
    )


def apply_relaxed_bot_env(*, execute_orders: bool = True) -> None:
    """Inyecta variables de entorno relajadas (idempotente por proceso)."""
    relaxed: dict[str, str] = {
        "ALPACA_MIN_VOLUME_Z": str(ALPACA_RELAXED_MIN_VOLUME_Z),
        "ALPACA_MIN_CLOSE_POSITION": str(ALPACA_RELAXED_MIN_CLOSE_POSITION),
        "ALPACA_PROB_FLOOR": str(ALPACA_RELAXED_PROB_FLOOR),
        "ALPACA_SIZE_DOWN_BAND": str(ALPACA_RELAXED_SIZE_DOWN_BAND),
        "ALPACA_R2_MIN_SCORE": str(ALPACA_RELAXED_R2_MIN_SCORE),
        "ALPACA_R2_GATE_VETO_THRESHOLD": str(ALPACA_RELAXED_R2_GATE_VETO),
        "ALPACA_R2_CONFLUENCE_MIN_ENGINES": str(ALPACA_RELAXED_R2_CONFLUENCE_MIN),
        "EQUITY_L2_GATE_ENABLED": "false",
        "EQUITY_L2_GATE_BLOCK_MISSING": "false",
        "BINGX_MIN_DECISION_SCORE": str(BINGX_RELAXED_MIN_DECISION_SCORE),
        "BINGX_MIN_PREDICTIVE_CONFIDENCE": str(BINGX_RELAXED_MIN_PREDICTIVE_CONF),
        "BINGX_REQUIRE_L2_FOR_EQUITY_LIVE": "false",
        "RISK_NO_TRADE_PROVIDER_DEGRADED": "false",
        "RISK_MIN_L2_QUALITY_SCORE": "0.05",
        "RISK_MAX_OPEN_POSITIONS": "8",
        "BINGX_ZONE_VETO_ENABLED": "false",
        "OPTIONS_STRATEGY_RELAXED_VETOS": "true",
        "OPTIONS_STRATEGY_MIN_GLOBAL_CONFIDENCE": "0.18",
        "OPTIONS_RELAXED_MIN_CHAIN_LIQUIDITY": str(OPTIONS_RELAXED_MIN_CHAIN_LIQUIDITY),
        "OPTIONS_UNIVERSE_DTE_MIN": str(OPTIONS_ROUTE1_DTE_MIN),
        "OPTIONS_UNIVERSE_DTE_MAX": str(OPTIONS_ROUTE1_DTE_MAX),
        "OPTIONS_MIN_OPEN_INTEREST": str(OPTIONS_ROUTE1_MIN_OPEN_INTEREST),
        "OPTIONS_MIN_DAILY_VOLUME": str(OPTIONS_ROUTE1_MIN_DAILY_VOLUME),
        "OPTIONS_CHAIN_HYDRATION_MIN_LEGS": str(OPTIONS_CHAIN_HYDRATION_MIN_LEGS),
        "OPTIONS_ROUTE1_LENIENT": "true",
        "ALPACA_OPTIONS_R1_MAX_PER_CYCLE": str(ALPACA_OPTIONS_R1_MAX_PER_CYCLE),
        "ALPACA_OPTIONS_R2_MAX_PER_CYCLE": str(ALPACA_OPTIONS_R2_MAX_PER_CYCLE),
        "BINGX_OMIT_REDUCE_ONLY": "true",
        "ALPACA_OPTIONS_ENABLED": "true",
        "ALPACA_OPTIONS_PRIORITY_EQUITY": "true",
    }
    if execute_orders:
        relaxed["ALPACA_TRADING_MODE"] = os.getenv("ALPACA_TRADING_MODE", "paper")
        relaxed["ALPACA_DRY_RUN"] = "false"
        relaxed["BINGX_DRY_RUN"] = "false"
        relaxed["BINGX_BOT_ENABLE_LIVE"] = "true"
        if not os.getenv("BINGX_BOT_TRADING_ENV"):
            relaxed["BINGX_BOT_TRADING_ENV"] = "prod-vst"
    _force_env(relaxed)


__all__ = [
    "ALPACA_PAPER_EQUITY_USD",
    "ALPACA_NOTIONAL_PER_TRADE_USD",
    "BINGX_DEMO_EQUITY_USDT",
    "BINGX_NOTIONAL_PER_TRADE_USDT",
    "DEFAULT_BOT_CYCLE_INTERVAL_S",
    "VERIFICATION_ALPACA_NOTIONAL_USD",
    "VERIFICATION_BINGX_NOTIONAL_USDT",
    "apply_paper_demo_account_env",
    "apply_relaxed_bot_env",
    "apply_verification_session_env",
]
