"""Umbrales de enriquecimiento R1 para Options Strategy. # [PD-8][TH]"""

from __future__ import annotations

L2_OFI_BLEND_WEIGHT: float = 0.35
HYBRID_OPTIONS_BLEND_WEIGHT: float = 0.40
PREDICTIVE_BRIDGE_BLEND_WEIGHT: float = 0.25
INTRADAY_5M_INTERVAL: str = "5m"
INTRADAY_5M_LOOKBACK_DAYS: int = 14
INTRADAY_5M_MIN_BARS: int = 30
INTRADAY_5M_MAX_BARS: int = 500
FUSION_HYBRID_CONF_WEIGHT: float = 0.35
FUSION_L2_CONF_WEIGHT: float = 0.30

__all__ = [
    "FUSION_HYBRID_CONF_WEIGHT",
    "FUSION_L2_CONF_WEIGHT",
    "HYBRID_OPTIONS_BLEND_WEIGHT",
    "INTRADAY_5M_INTERVAL",
    "INTRADAY_5M_LOOKBACK_DAYS",
    "INTRADAY_5M_MAX_BARS",
    "INTRADAY_5M_MIN_BARS",
    "L2_OFI_BLEND_WEIGHT",
    "PREDICTIVE_BRIDGE_BLEND_WEIGHT",
]
